version: '3.9'
services:
  app:
    restart: always
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 80
    #command: gunicorn api.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:80
    expose:
      - 80
    env_file:
      - .env
    depends_on:
      - postgres
      - minio

  minio:
    image: minio/minio:RELEASE.2021-04-06T23-11-00Z
    volumes:
      - minio-data:/minio-data
    env_file:
      - .env
    command: minio server /minio-data/minio/

  postgres:
    restart: always
    image: postgres:15.3-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  postgres-data:
  minio-data: